const styles = {
  app: { minHeight: '100vh', background: '#0a0f1e', color: '#e2e8f0', fontFamily: "'Inter', sans-serif" },
  nav: { background: '#0d1526', borderBottom: '1px solid #1e2d4a', padding: '0 2rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '56px' },
  navBrand: { display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' },
  navLogo: { width: 34, height: 34, borderRadius: 8, background: 'linear-gradient(135deg, #3b82f6, #6366f1)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16 },
  navTitle: { fontWeight: 700, fontSize: 16, color: '#f1f5f9' },
  navSub: { fontSize: 12, color: '#64748b' },
  container: { maxWidth: 1100, margin: '0 auto', padding: '2rem 1.5rem' },
  tabBar: { display: 'flex', background: '#111827', borderRadius: 10, padding: 4, gap: 2, marginBottom: '1.5rem', width: 'fit-content' },
  tab: (active) => ({ padding: '8px 20px', borderRadius: 7, border: 'none', cursor: 'pointer', fontSize: 14, fontWeight: 500, transition: 'all 0.2s', background: active ? '#3b82f6' : 'transparent', color: active ? '#fff' : '#94a3b8' }),
  sectionHeader: { marginBottom: '1.5rem' },
  sectionTitle: { fontSize: 22, fontWeight: 700, color: '#f1f5f9', marginBottom: 4 },
  sectionSub: { fontSize: 14, color: '#64748b' },
  card: { background: '#111827', border: '1px solid #1e2d4a', borderRadius: 12, overflow: 'hidden', transition: 'transform 0.2s, border-color 0.2s', cursor: 'pointer' },
  cardHover: { transform: 'translateY(-2px)', borderColor: '#3b82f6' },
  grid3: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1.25rem' },
  eventCardTop: (color) => ({ height: 6, background: color || '#3b82f6' }),
  eventCardBody: { padding: '1.25rem' },
  eventTitle: { fontSize: 17, fontWeight: 700, color: '#f1f5f9', marginBottom: 6 },
  eventDesc: { fontSize: 13, color: '#94a3b8', marginBottom: '1rem', lineHeight: 1.6 },
  metaRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: '#64748b', background: '#0d1526', borderRadius: 8, padding: '8px 12px', marginBottom: 8 },
  badge: (color) => ({ fontSize: 11, fontWeight: 600, padding: '3px 8px', borderRadius: 20, background: color + '22', color: color }),
  btn: (variant = 'primary') => ({
    padding: '9px 18px', borderRadius: 8, border: 'none', cursor: 'pointer', fontSize: 14, fontWeight: 600, transition: 'all 0.2s',
    background: variant === 'primary' ? '#3b82f6' : variant === 'danger' ? '#ef4444' : variant === 'ghost' ? 'transparent' : variant === 'success' ? '#10b981' : '#1e2d4a',
    color: variant === 'ghost' ? '#94a3b8' : '#fff',
    opacity: 1,
  }),
  btnDisabled: { opacity: 0.5, cursor: 'not-allowed' },
  searchRow: { display: 'flex', gap: '1rem', marginBottom: '1.5rem', flexWrap: 'wrap', alignItems: 'center' },
  input: { background: '#111827', border: '1px solid #1e2d4a', borderRadius: 8, padding: '9px 14px', color: '#e2e8f0', fontSize: 14, outline: 'none', flex: 1, minWidth: 200 },
  select: { background: '#111827', border: '1px solid #1e2d4a', borderRadius: 8, padding: '9px 14px', color: '#e2e8f0', fontSize: 14, outline: 'none' },
  progressBar: (pct, color) => ({ height: 4, borderRadius: 4, background: '#1e2d4a', overflow: 'hidden', margin: '4px 0 8px' }),
  progressFill: (pct, color) => ({ height: '100%', width: pct + '%', background: pct > 80 ? '#ef4444' : pct > 60 ? '#f59e0b' : '#3b82f6', borderRadius: 4 }),
  modal: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 999, padding: '1rem' },
  modalBox: { background: '#111827', border: '1px solid #1e2d4a', borderRadius: 16, padding: '2rem', width: '100%', maxWidth: 520, maxHeight: '90vh', overflowY: 'auto' },
  label: { display: 'block', fontSize: 13, color: '#94a3b8', marginBottom: 6, fontWeight: 500 },
  formInput: { display: 'block', width: '100%', background: '#0d1526', border: '1px solid #1e2d4a', borderRadius: 8, padding: '9px 14px', color: '#e2e8f0', fontSize: 14, outline: 'none', marginBottom: '1rem', boxSizing: 'border-box' },
  formGroup: { marginBottom: '1rem' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: { textAlign: 'left', padding: '10px 14px', color: '#64748b', fontWeight: 600, fontSize: 12, textTransform: 'uppercase', borderBottom: '1px solid #1e2d4a' },
  td: { padding: '12px 14px', borderBottom: '1px solid #0d1526', color: '#cbd5e1' },
  emptyState: { textAlign: 'center', padding: '4rem 2rem', color: '#64748b' },
  notif: (type) => ({ position: 'fixed', top: 20, right: 20, zIndex: 9999, padding: '12px 20px', borderRadius: 10, fontSize: 14, fontWeight: 500, background: type === 'success' ? '#10b981' : type === 'danger' ? '#ef4444' : '#3b82f6', color: '#fff', boxShadow: '0 4px 20px rgba(0,0,0,0.3)' }),
};

export default styles;
